# Use postgres/example user/password credentials
# version: '3.1'
# services:
#   db:
#     image: postgres
#     restart: always
#     environment:
#       POSTGRES_PASSWORD: example
#     ports:
#       - 5432:5432
version: '3.2'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
    - $PWD/data/postgres_data:/var/lib/postgresql/data
  web:
    # build: .
    # depends_on:
    #   - db
    image: lainermeister/agile-beluga-products
    user: node
    working_dir: /server
    environment:
      - NODE_ENV=production
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
    volumes:
      - ./:/server
    ports:
      - "3000:3000"
    # command: "npm start"
  