# Use postgres/example user/password credentials
# version: '3.1'
# services:
#   db:
#     image: postgres
#     restart: always
#     environment:
#       POSTGRES_PASSWORD: example
#     ports:
#       - 5432:5432
version: '2'
services:
  web:
    build: .
    depends_on:
      - db
    image: "node:8"
    user: "node"
    working_dir: /server
    environment:
      - NODE_ENV=production
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
    volumes:
      - ./:/server
    ports:
      - "3000:3000"
    command: "npm start"
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
    - $PWD/db/postgres_data:/var/lib/postgresql/data